/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as humanFiGovernanceSol from "./HumanFiGovernance.sol";
export type { humanFiGovernanceSol };
export type { MockWLD } from "./MockWLD";
