/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ConstructedCloneFactory,
  ConstructedCloneFactoryInterface,
} from "../../../../@gnosis.pm/util-contracts/contracts/ConstructedCloneFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "clone",
        type: "address",
      },
    ],
    name: "CloneCreated",
    type: "event",
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "cloneConstructor",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ConstructedCloneFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ConstructedCloneFactoryInterface {
    return new Interface(_abi) as ConstructedCloneFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ConstructedCloneFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ConstructedCloneFactory;
  }
}
