/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HumanFiGovernance__factory } from "./HumanFiGovernance__factory";
export { IWorldID__factory } from "./IWorldID__factory";
