/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155 } from "./ERC1155";
export type { ERC1155TokenReceiver } from "./ERC1155TokenReceiver";
export type { IERC1155 } from "./IERC1155";
export type { IERC1155TokenReceiver } from "./IERC1155TokenReceiver";
