/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  FixedProductMarketMakerData,
  FixedProductMarketMakerDataInterface,
} from "../../../../../@gnosis.pm/conditional-tokens-market-makers/contracts/FixedProductMarketMaker.sol/FixedProductMarketMakerData";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "investmentAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "outcomeIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "outcomeTokensBought",
        type: "uint256",
      },
    ],
    name: "FPMMBuy",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "funder",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "amountsAdded",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "sharesMinted",
        type: "uint256",
      },
    ],
    name: "FPMMFundingAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "funder",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "amountsRemoved",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "collateralRemovedFromFeePool",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "sharesBurnt",
        type: "uint256",
      },
    ],
    name: "FPMMFundingRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "returnAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "outcomeIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "outcomeTokensSold",
        type: "uint256",
      },
    ],
    name: "FPMMSell",
    type: "event",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603e80601d6000396000f3fe6080604052600080fdfea265627a7a723158205bd05917777fce1357395e7b763c88c792d4c96ca6239a13a7990ff2c74b6b7964736f6c63430005110032";

type FixedProductMarketMakerDataConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FixedProductMarketMakerDataConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FixedProductMarketMakerData__factory extends ContractFactory {
  constructor(...args: FixedProductMarketMakerDataConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FixedProductMarketMakerData & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): FixedProductMarketMakerData__factory {
    return super.connect(runner) as FixedProductMarketMakerData__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FixedProductMarketMakerDataInterface {
    return new Interface(_abi) as FixedProductMarketMakerDataInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FixedProductMarketMakerData {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as FixedProductMarketMakerData;
  }
}
