/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface FixedProductMarketMakerFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cloneConstructor"
      | "createFixedProductMarketMaker"
      | "implementationMaster"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CloneCreated"
      | "FPMMBuy"
      | "FPMMFundingAdded"
      | "FPMMFundingRemoved"
      | "FPMMSell"
      | "FixedProductMarketMakerCreation"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cloneConstructor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createFixedProductMarketMaker",
    values: [AddressLike, AddressLike, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "implementationMaster",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "cloneConstructor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createFixedProductMarketMaker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementationMaster",
    data: BytesLike
  ): Result;
}

export namespace CloneCreatedEvent {
  export type InputTuple = [target: AddressLike, clone: AddressLike];
  export type OutputTuple = [target: string, clone: string];
  export interface OutputObject {
    target: string;
    clone: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FPMMBuyEvent {
  export type InputTuple = [
    buyer: AddressLike,
    investmentAmount: BigNumberish,
    feeAmount: BigNumberish,
    outcomeIndex: BigNumberish,
    outcomeTokensBought: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    investmentAmount: bigint,
    feeAmount: bigint,
    outcomeIndex: bigint,
    outcomeTokensBought: bigint
  ];
  export interface OutputObject {
    buyer: string;
    investmentAmount: bigint;
    feeAmount: bigint;
    outcomeIndex: bigint;
    outcomeTokensBought: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FPMMFundingAddedEvent {
  export type InputTuple = [
    funder: AddressLike,
    amountsAdded: BigNumberish[],
    sharesMinted: BigNumberish
  ];
  export type OutputTuple = [
    funder: string,
    amountsAdded: bigint[],
    sharesMinted: bigint
  ];
  export interface OutputObject {
    funder: string;
    amountsAdded: bigint[];
    sharesMinted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FPMMFundingRemovedEvent {
  export type InputTuple = [
    funder: AddressLike,
    amountsRemoved: BigNumberish[],
    collateralRemovedFromFeePool: BigNumberish,
    sharesBurnt: BigNumberish
  ];
  export type OutputTuple = [
    funder: string,
    amountsRemoved: bigint[],
    collateralRemovedFromFeePool: bigint,
    sharesBurnt: bigint
  ];
  export interface OutputObject {
    funder: string;
    amountsRemoved: bigint[];
    collateralRemovedFromFeePool: bigint;
    sharesBurnt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FPMMSellEvent {
  export type InputTuple = [
    seller: AddressLike,
    returnAmount: BigNumberish,
    feeAmount: BigNumberish,
    outcomeIndex: BigNumberish,
    outcomeTokensSold: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    returnAmount: bigint,
    feeAmount: bigint,
    outcomeIndex: bigint,
    outcomeTokensSold: bigint
  ];
  export interface OutputObject {
    seller: string;
    returnAmount: bigint;
    feeAmount: bigint;
    outcomeIndex: bigint;
    outcomeTokensSold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FixedProductMarketMakerCreationEvent {
  export type InputTuple = [
    creator: AddressLike,
    fixedProductMarketMaker: AddressLike,
    conditionalTokens: AddressLike,
    collateralToken: AddressLike,
    conditionIds: BytesLike[],
    fee: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    fixedProductMarketMaker: string,
    conditionalTokens: string,
    collateralToken: string,
    conditionIds: string[],
    fee: bigint
  ];
  export interface OutputObject {
    creator: string;
    fixedProductMarketMaker: string;
    conditionalTokens: string;
    collateralToken: string;
    conditionIds: string[];
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FixedProductMarketMakerFactory extends BaseContract {
  connect(runner?: ContractRunner | null): FixedProductMarketMakerFactory;
  waitForDeployment(): Promise<this>;

  interface: FixedProductMarketMakerFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cloneConstructor: TypedContractMethod<
    [consData: BytesLike],
    [void],
    "nonpayable"
  >;

  createFixedProductMarketMaker: TypedContractMethod<
    [
      conditionalTokens: AddressLike,
      collateralToken: AddressLike,
      conditionIds: BytesLike[],
      fee: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  implementationMaster: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cloneConstructor"
  ): TypedContractMethod<[consData: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createFixedProductMarketMaker"
  ): TypedContractMethod<
    [
      conditionalTokens: AddressLike,
      collateralToken: AddressLike,
      conditionIds: BytesLike[],
      fee: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "implementationMaster"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CloneCreated"
  ): TypedContractEvent<
    CloneCreatedEvent.InputTuple,
    CloneCreatedEvent.OutputTuple,
    CloneCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FPMMBuy"
  ): TypedContractEvent<
    FPMMBuyEvent.InputTuple,
    FPMMBuyEvent.OutputTuple,
    FPMMBuyEvent.OutputObject
  >;
  getEvent(
    key: "FPMMFundingAdded"
  ): TypedContractEvent<
    FPMMFundingAddedEvent.InputTuple,
    FPMMFundingAddedEvent.OutputTuple,
    FPMMFundingAddedEvent.OutputObject
  >;
  getEvent(
    key: "FPMMFundingRemoved"
  ): TypedContractEvent<
    FPMMFundingRemovedEvent.InputTuple,
    FPMMFundingRemovedEvent.OutputTuple,
    FPMMFundingRemovedEvent.OutputObject
  >;
  getEvent(
    key: "FPMMSell"
  ): TypedContractEvent<
    FPMMSellEvent.InputTuple,
    FPMMSellEvent.OutputTuple,
    FPMMSellEvent.OutputObject
  >;
  getEvent(
    key: "FixedProductMarketMakerCreation"
  ): TypedContractEvent<
    FixedProductMarketMakerCreationEvent.InputTuple,
    FixedProductMarketMakerCreationEvent.OutputTuple,
    FixedProductMarketMakerCreationEvent.OutputObject
  >;

  filters: {
    "CloneCreated(address,address)": TypedContractEvent<
      CloneCreatedEvent.InputTuple,
      CloneCreatedEvent.OutputTuple,
      CloneCreatedEvent.OutputObject
    >;
    CloneCreated: TypedContractEvent<
      CloneCreatedEvent.InputTuple,
      CloneCreatedEvent.OutputTuple,
      CloneCreatedEvent.OutputObject
    >;

    "FPMMBuy(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FPMMBuyEvent.InputTuple,
      FPMMBuyEvent.OutputTuple,
      FPMMBuyEvent.OutputObject
    >;
    FPMMBuy: TypedContractEvent<
      FPMMBuyEvent.InputTuple,
      FPMMBuyEvent.OutputTuple,
      FPMMBuyEvent.OutputObject
    >;

    "FPMMFundingAdded(address,uint256[],uint256)": TypedContractEvent<
      FPMMFundingAddedEvent.InputTuple,
      FPMMFundingAddedEvent.OutputTuple,
      FPMMFundingAddedEvent.OutputObject
    >;
    FPMMFundingAdded: TypedContractEvent<
      FPMMFundingAddedEvent.InputTuple,
      FPMMFundingAddedEvent.OutputTuple,
      FPMMFundingAddedEvent.OutputObject
    >;

    "FPMMFundingRemoved(address,uint256[],uint256,uint256)": TypedContractEvent<
      FPMMFundingRemovedEvent.InputTuple,
      FPMMFundingRemovedEvent.OutputTuple,
      FPMMFundingRemovedEvent.OutputObject
    >;
    FPMMFundingRemoved: TypedContractEvent<
      FPMMFundingRemovedEvent.InputTuple,
      FPMMFundingRemovedEvent.OutputTuple,
      FPMMFundingRemovedEvent.OutputObject
    >;

    "FPMMSell(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FPMMSellEvent.InputTuple,
      FPMMSellEvent.OutputTuple,
      FPMMSellEvent.OutputObject
    >;
    FPMMSell: TypedContractEvent<
      FPMMSellEvent.InputTuple,
      FPMMSellEvent.OutputTuple,
      FPMMSellEvent.OutputObject
    >;

    "FixedProductMarketMakerCreation(address,address,address,address,bytes32[],uint256)": TypedContractEvent<
      FixedProductMarketMakerCreationEvent.InputTuple,
      FixedProductMarketMakerCreationEvent.OutputTuple,
      FixedProductMarketMakerCreationEvent.OutputObject
    >;
    FixedProductMarketMakerCreation: TypedContractEvent<
      FixedProductMarketMakerCreationEvent.InputTuple,
      FixedProductMarketMakerCreationEvent.OutputTuple,
      FixedProductMarketMakerCreationEvent.OutputObject
    >;
  };
}
