/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface FixedProductMarketMakerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addFunding"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "buy"
      | "calcBuyAmount"
      | "calcSellAmount"
      | "collateralToken"
      | "collectedFees"
      | "conditionIds"
      | "conditionalTokens"
      | "decreaseAllowance"
      | "fee"
      | "feesWithdrawableBy"
      | "increaseAllowance"
      | "onERC1155BatchReceived"
      | "onERC1155Received"
      | "removeFunding"
      | "sell"
      | "supportsInterface"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "FPMMBuy"
      | "FPMMFundingAdded"
      | "FPMMFundingRemoved"
      | "FPMMSell"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addFunding",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calcBuyAmount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calcSellAmount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "conditionIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "conditionalTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feesWithdrawableBy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFunding",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addFunding", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calcBuyAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcSellAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conditionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conditionalTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feesWithdrawableBy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFunding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FPMMBuyEvent {
  export type InputTuple = [
    buyer: AddressLike,
    investmentAmount: BigNumberish,
    feeAmount: BigNumberish,
    outcomeIndex: BigNumberish,
    outcomeTokensBought: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    investmentAmount: bigint,
    feeAmount: bigint,
    outcomeIndex: bigint,
    outcomeTokensBought: bigint
  ];
  export interface OutputObject {
    buyer: string;
    investmentAmount: bigint;
    feeAmount: bigint;
    outcomeIndex: bigint;
    outcomeTokensBought: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FPMMFundingAddedEvent {
  export type InputTuple = [
    funder: AddressLike,
    amountsAdded: BigNumberish[],
    sharesMinted: BigNumberish
  ];
  export type OutputTuple = [
    funder: string,
    amountsAdded: bigint[],
    sharesMinted: bigint
  ];
  export interface OutputObject {
    funder: string;
    amountsAdded: bigint[];
    sharesMinted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FPMMFundingRemovedEvent {
  export type InputTuple = [
    funder: AddressLike,
    amountsRemoved: BigNumberish[],
    collateralRemovedFromFeePool: BigNumberish,
    sharesBurnt: BigNumberish
  ];
  export type OutputTuple = [
    funder: string,
    amountsRemoved: bigint[],
    collateralRemovedFromFeePool: bigint,
    sharesBurnt: bigint
  ];
  export interface OutputObject {
    funder: string;
    amountsRemoved: bigint[];
    collateralRemovedFromFeePool: bigint;
    sharesBurnt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FPMMSellEvent {
  export type InputTuple = [
    seller: AddressLike,
    returnAmount: BigNumberish,
    feeAmount: BigNumberish,
    outcomeIndex: BigNumberish,
    outcomeTokensSold: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    returnAmount: bigint,
    feeAmount: bigint,
    outcomeIndex: bigint,
    outcomeTokensSold: bigint
  ];
  export interface OutputObject {
    seller: string;
    returnAmount: bigint;
    feeAmount: bigint;
    outcomeIndex: bigint;
    outcomeTokensSold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FixedProductMarketMaker extends BaseContract {
  connect(runner?: ContractRunner | null): FixedProductMarketMaker;
  waitForDeployment(): Promise<this>;

  interface: FixedProductMarketMakerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addFunding: TypedContractMethod<
    [addedFunds: BigNumberish, distributionHint: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  buy: TypedContractMethod<
    [
      investmentAmount: BigNumberish,
      outcomeIndex: BigNumberish,
      minOutcomeTokensToBuy: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  calcBuyAmount: TypedContractMethod<
    [investmentAmount: BigNumberish, outcomeIndex: BigNumberish],
    [bigint],
    "view"
  >;

  calcSellAmount: TypedContractMethod<
    [returnAmount: BigNumberish, outcomeIndex: BigNumberish],
    [bigint],
    "view"
  >;

  collateralToken: TypedContractMethod<[], [string], "view">;

  collectedFees: TypedContractMethod<[], [bigint], "view">;

  conditionIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  conditionalTokens: TypedContractMethod<[], [string], "view">;

  decreaseAllowance: TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  fee: TypedContractMethod<[], [bigint], "view">;

  feesWithdrawableBy: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  increaseAllowance: TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  onERC1155BatchReceived: TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  onERC1155Received: TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  removeFunding: TypedContractMethod<
    [sharesToBurn: BigNumberish],
    [void],
    "nonpayable"
  >;

  sell: TypedContractMethod<
    [
      returnAmount: BigNumberish,
      outcomeIndex: BigNumberish,
      maxOutcomeTokensToSell: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [sender: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addFunding"
  ): TypedContractMethod<
    [addedFunds: BigNumberish, distributionHint: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [
      investmentAmount: BigNumberish,
      outcomeIndex: BigNumberish,
      minOutcomeTokensToBuy: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calcBuyAmount"
  ): TypedContractMethod<
    [investmentAmount: BigNumberish, outcomeIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calcSellAmount"
  ): TypedContractMethod<
    [returnAmount: BigNumberish, outcomeIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "collateralToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "collectedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "conditionIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "conditionalTokens"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decreaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feesWithdrawableBy"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "increaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC1155BatchReceived"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC1155Received"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      from: AddressLike,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeFunding"
  ): TypedContractMethod<[sharesToBurn: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [
      returnAmount: BigNumberish,
      outcomeIndex: BigNumberish,
      maxOutcomeTokensToSell: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [sender: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "FPMMBuy"
  ): TypedContractEvent<
    FPMMBuyEvent.InputTuple,
    FPMMBuyEvent.OutputTuple,
    FPMMBuyEvent.OutputObject
  >;
  getEvent(
    key: "FPMMFundingAdded"
  ): TypedContractEvent<
    FPMMFundingAddedEvent.InputTuple,
    FPMMFundingAddedEvent.OutputTuple,
    FPMMFundingAddedEvent.OutputObject
  >;
  getEvent(
    key: "FPMMFundingRemoved"
  ): TypedContractEvent<
    FPMMFundingRemovedEvent.InputTuple,
    FPMMFundingRemovedEvent.OutputTuple,
    FPMMFundingRemovedEvent.OutputObject
  >;
  getEvent(
    key: "FPMMSell"
  ): TypedContractEvent<
    FPMMSellEvent.InputTuple,
    FPMMSellEvent.OutputTuple,
    FPMMSellEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "FPMMBuy(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FPMMBuyEvent.InputTuple,
      FPMMBuyEvent.OutputTuple,
      FPMMBuyEvent.OutputObject
    >;
    FPMMBuy: TypedContractEvent<
      FPMMBuyEvent.InputTuple,
      FPMMBuyEvent.OutputTuple,
      FPMMBuyEvent.OutputObject
    >;

    "FPMMFundingAdded(address,uint256[],uint256)": TypedContractEvent<
      FPMMFundingAddedEvent.InputTuple,
      FPMMFundingAddedEvent.OutputTuple,
      FPMMFundingAddedEvent.OutputObject
    >;
    FPMMFundingAdded: TypedContractEvent<
      FPMMFundingAddedEvent.InputTuple,
      FPMMFundingAddedEvent.OutputTuple,
      FPMMFundingAddedEvent.OutputObject
    >;

    "FPMMFundingRemoved(address,uint256[],uint256,uint256)": TypedContractEvent<
      FPMMFundingRemovedEvent.InputTuple,
      FPMMFundingRemovedEvent.OutputTuple,
      FPMMFundingRemovedEvent.OutputObject
    >;
    FPMMFundingRemoved: TypedContractEvent<
      FPMMFundingRemovedEvent.InputTuple,
      FPMMFundingRemovedEvent.OutputTuple,
      FPMMFundingRemovedEvent.OutputObject
    >;

    "FPMMSell(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FPMMSellEvent.InputTuple,
      FPMMSellEvent.OutputTuple,
      FPMMSellEvent.OutputObject
    >;
    FPMMSell: TypedContractEvent<
      FPMMSellEvent.InputTuple,
      FPMMSellEvent.OutputTuple,
      FPMMSellEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
