/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../../common";

export interface FixedProductMarketMakerDataInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "FPMMBuy"
      | "FPMMFundingAdded"
      | "FPMMFundingRemoved"
      | "FPMMSell"
  ): EventFragment;
}

export namespace FPMMBuyEvent {
  export type InputTuple = [
    buyer: AddressLike,
    investmentAmount: BigNumberish,
    feeAmount: BigNumberish,
    outcomeIndex: BigNumberish,
    outcomeTokensBought: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    investmentAmount: bigint,
    feeAmount: bigint,
    outcomeIndex: bigint,
    outcomeTokensBought: bigint
  ];
  export interface OutputObject {
    buyer: string;
    investmentAmount: bigint;
    feeAmount: bigint;
    outcomeIndex: bigint;
    outcomeTokensBought: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FPMMFundingAddedEvent {
  export type InputTuple = [
    funder: AddressLike,
    amountsAdded: BigNumberish[],
    sharesMinted: BigNumberish
  ];
  export type OutputTuple = [
    funder: string,
    amountsAdded: bigint[],
    sharesMinted: bigint
  ];
  export interface OutputObject {
    funder: string;
    amountsAdded: bigint[];
    sharesMinted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FPMMFundingRemovedEvent {
  export type InputTuple = [
    funder: AddressLike,
    amountsRemoved: BigNumberish[],
    collateralRemovedFromFeePool: BigNumberish,
    sharesBurnt: BigNumberish
  ];
  export type OutputTuple = [
    funder: string,
    amountsRemoved: bigint[],
    collateralRemovedFromFeePool: bigint,
    sharesBurnt: bigint
  ];
  export interface OutputObject {
    funder: string;
    amountsRemoved: bigint[];
    collateralRemovedFromFeePool: bigint;
    sharesBurnt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FPMMSellEvent {
  export type InputTuple = [
    seller: AddressLike,
    returnAmount: BigNumberish,
    feeAmount: BigNumberish,
    outcomeIndex: BigNumberish,
    outcomeTokensSold: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    returnAmount: bigint,
    feeAmount: bigint,
    outcomeIndex: bigint,
    outcomeTokensSold: bigint
  ];
  export interface OutputObject {
    seller: string;
    returnAmount: bigint;
    feeAmount: bigint;
    outcomeIndex: bigint;
    outcomeTokensSold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FixedProductMarketMakerData extends BaseContract {
  connect(runner?: ContractRunner | null): FixedProductMarketMakerData;
  waitForDeployment(): Promise<this>;

  interface: FixedProductMarketMakerDataInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "FPMMBuy"
  ): TypedContractEvent<
    FPMMBuyEvent.InputTuple,
    FPMMBuyEvent.OutputTuple,
    FPMMBuyEvent.OutputObject
  >;
  getEvent(
    key: "FPMMFundingAdded"
  ): TypedContractEvent<
    FPMMFundingAddedEvent.InputTuple,
    FPMMFundingAddedEvent.OutputTuple,
    FPMMFundingAddedEvent.OutputObject
  >;
  getEvent(
    key: "FPMMFundingRemoved"
  ): TypedContractEvent<
    FPMMFundingRemovedEvent.InputTuple,
    FPMMFundingRemovedEvent.OutputTuple,
    FPMMFundingRemovedEvent.OutputObject
  >;
  getEvent(
    key: "FPMMSell"
  ): TypedContractEvent<
    FPMMSellEvent.InputTuple,
    FPMMSellEvent.OutputTuple,
    FPMMSellEvent.OutputObject
  >;

  filters: {
    "FPMMBuy(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FPMMBuyEvent.InputTuple,
      FPMMBuyEvent.OutputTuple,
      FPMMBuyEvent.OutputObject
    >;
    FPMMBuy: TypedContractEvent<
      FPMMBuyEvent.InputTuple,
      FPMMBuyEvent.OutputTuple,
      FPMMBuyEvent.OutputObject
    >;

    "FPMMFundingAdded(address,uint256[],uint256)": TypedContractEvent<
      FPMMFundingAddedEvent.InputTuple,
      FPMMFundingAddedEvent.OutputTuple,
      FPMMFundingAddedEvent.OutputObject
    >;
    FPMMFundingAdded: TypedContractEvent<
      FPMMFundingAddedEvent.InputTuple,
      FPMMFundingAddedEvent.OutputTuple,
      FPMMFundingAddedEvent.OutputObject
    >;

    "FPMMFundingRemoved(address,uint256[],uint256,uint256)": TypedContractEvent<
      FPMMFundingRemovedEvent.InputTuple,
      FPMMFundingRemovedEvent.OutputTuple,
      FPMMFundingRemovedEvent.OutputObject
    >;
    FPMMFundingRemoved: TypedContractEvent<
      FPMMFundingRemovedEvent.InputTuple,
      FPMMFundingRemovedEvent.OutputTuple,
      FPMMFundingRemovedEvent.OutputObject
    >;

    "FPMMSell(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FPMMSellEvent.InputTuple,
      FPMMSellEvent.OutputTuple,
      FPMMSellEvent.OutputObject
    >;
    FPMMSell: TypedContractEvent<
      FPMMSellEvent.InputTuple,
      FPMMSellEvent.OutputTuple,
      FPMMSellEvent.OutputObject
    >;
  };
}
