/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155__factory } from "./ERC1155__factory";
export { ERC1155TokenReceiver__factory } from "./ERC1155TokenReceiver__factory";
export { IERC1155__factory } from "./IERC1155__factory";
export { IERC1155TokenReceiver__factory } from "./IERC1155TokenReceiver__factory";
